import "./globals.css";
import { Lora } from "next/font/google";
import Header from "@/components/Header";

const lora = Lora({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lora.className}>
        <header className="px-6 pt-6">
          <Header />
        </header>
        {children}
      </body>
    </html>
  );
}
